name: provider_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.6
  cupertino_icons: ^1.0.2
  date_format: ^2.0.6
  firebase_auth: ^3.7.0
  flutter:
    sdk: flutter
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
